name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: List files
        run: ls
      
      - name: Package
        run: |
          ls
          mkdir out
          7z a "./out/PluginTemplate.zip" ./PluginTemplate/* -r -mx=9 
          
      - name: Upload to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: PluginTemplate.zip
          path: ./out/*.zip
    
      - name: Upload to release
        uses: ncipollo/release-action@v1
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          artifacts: ./out/*.zip
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}
 